-- Script de création des tables pour le Payment Service (MySQL / PostgreSQL / H2 compatible)

CREATE TABLE IF NOT EXISTS wallets (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    user_id VARCHAR(100) NOT NULL UNIQUE,
    card_id VARCHAR(100) NOT NULL UNIQUE,
    balance DECIMAL(10,2) NOT NULL DEFAULT 0.00,
    currency VARCHAR(10) NOT NULL DEFAULT 'XOF',
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS payment_transactions (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    transaction_ref VARCHAR(100) NOT NULL UNIQUE,
    user_id VARCHAR(100) NOT NULL,
    card_id VARCHAR(100) NOT NULL,
    type VARCHAR(30) NOT NULL, -- RECHARGE_WAVE, RIDE_DEBIT, REFUND
    amount DECIMAL(10,2) NOT NULL,
    balance_after DECIMAL(10,2) NOT NULL,
    currency VARCHAR(10) NOT NULL DEFAULT 'XOF',
    status VARCHAR(20) NOT NULL, -- SUCCESS, FAILED, PENDING
    payment_method VARCHAR(50), -- WAVE, WALLET
    ride_id VARCHAR(100),
    line_id VARCHAR(100),
    bus_id VARCHAR(100),
    description VARCHAR(255),
    timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS fare_rules (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    line_id VARCHAR(100) NOT NULL,
    line_name VARCHAR(100) NOT NULL,
    passenger_type VARCHAR(30) NOT NULL, -- REGULAR, STUDENT, SENIOR, DISABILITY
    base_fare DECIMAL(10,2) NOT NULL,
    active BOOLEAN DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS fraud_alerts (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    user_id VARCHAR(100) NOT NULL,
    card_id VARCHAR(100) NOT NULL,
    fraud_type VARCHAR(50) NOT NULL, -- RAPID_TRANSACTIONS, INSUFFICIENT_FUNDS_REPEATED, UNUSUAL_AMOUNT
    risk_level VARCHAR(20) NOT NULL, -- LOW, MEDIUM, HIGH, CRITICAL
    description VARCHAR(255) NOT NULL,
    timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    resolved BOOLEAN DEFAULT FALSE
);
